[workspace]

members = [
    "avalanche-macro",
    "avalanche",
    "avalanche-macro-test",
    "avalanche-web",
    "avalanche-web/examples/counter",
    "avalanche-web/examples/todomvc",
    "avalanche-web/examples/minesweeper",
]