[package]
name = "avalanche-web"
version = "0.0.0"
authors = ["Darius Jankauskas <d5926j@gmail.com>"]
edition = "2018"

[dependencies]
avalanche = {path = '../avalanche'}
wasm-bindgen = "0.2.58"
gloo = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "NodeList",
    "EventTarget",
    "Window",
    "Text",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "Event",
    "AnimationEvent",
    "CompositionEvent",
    "DragEvent",
    "FocusEvent",
    "KeyboardEvent",
    "MouseEvent",
    "MessageEvent",
    "ProgressEvent",
    "PointerEvent",
    "TransitionEvent",
    "TouchEvent",
    "WheelEvent"
]