[package]
name = "avalanche-web"
version = "0.0.0"
authors = ["Darius Jankauskas <d5926j@gmail.com>"]
edition = "2018"

[dependencies]
avalanche = {path = '../avalanche'}
wasm-bindgen = "0.2.58"
gloo = "0.2"

[dependencies.web-sys]
version = "0.3.35"
features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "EventTarget",
    "Window",
    "Text",
    "Event",
    "MouseEvent",
    "MessageEvent"
]