name: Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  MIRIFLAGS: "-Zmiri-ignore-leaks"

jobs:
  build_and_test:
    name: Cargo build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  miri_test:
    name: "Miri test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test --verbose